site_name: KepLemon
site_url: https://keplemon.citra.space/
use_directory_urls: false
repo_url: https://github.com/citra-space/keplemon

nav:
  - Home: index.md
  - Package Contents:
      - Core: submodules/index.md
      - Time: submodules/time.md
      - Enums: submodules/enums.md
      - Bodies: submodules/bodies.md
      - Elements: submodules/elements.md
      - Estimation: submodules/estimation.md
      - Events: submodules/events.md
  - Examples:
      - Propagation: examples/propagation_examples.md
      - Orbit Determination: examples/od_example.md
      - Close Approaches: examples/ca_examples.md
  - License: license.md

docs_dir: docs

theme:
  custom_dir: overrides
  name: material
  font:
    text: Montserrat
  logo: images/banner.png
  icon:
    menu: logo
  favicon: images/favicon.png
  palette:
    scheme: default
    primary: custom
    accent: custom
extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
            allow_inspection: false
            find_stubs_package: false
            show_root_heading: true
            show_root_full_path: false
          paths:
            - stubs/keplemon

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed
  - markdown_include.include:
      base_path: docs

extra:
  admonition:
    icons:
      note: null