# flake8: noqa
from enum import Enum

class CovarianceType(Enum):
    Inertial = ...
    Relative = ...
    Equinoctial = ...

class SAALKeyMode(Enum):
    NoDuplicates = ...
    DirectMemoryAccess = ...

class TimeSystem(Enum):
    UTC = ...
    TAI = ...
    TT = ...
    UT1 = ...

class Classification(Enum):
    Unclassified = ...
    Confidential = ...
    Secret = ...

class KeplerianType(Enum):
    MeanKozaiGP = ...
    MeanBrouwerGP = ...
    MeanBrouwerXP = ...
    Osculating = ...

class ReferenceFrame(Enum):
    TEME = ...
    J2000 = ...
    EFG = ...
    ECR = ...
